package main

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func main() {
	name := "world"
	if len(os.Args) > 1 {
		name = strings.Join(os.Args[1:], " ")
	}
	fmt.Printf("Hello, %s! 🎉\n", name)
	fmt.Printf("This was generated by a Go binary compiled and shipped inside a Claude Code plugin.\n")
	fmt.Printf("Binary built at: %s\n", time.Now().Format(time.RFC3339))
}
